### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by teekaytech** [Mikearaya/data-structure-and-algorithms#2]

**Comment by mariosknl** [comment]
Good job! Congrats

**Comment by Mikearaya** [comment]
**Thank you!!!** :bowing_man:

**Comment by mbabaliiryn** [comment]
Nice code implementation.

**Comment by frankopkusianwar** [comment]
Great work so far!! 
However, you could consider creating a .gitignore file for some files like Game.lock
